version: '3'

services:
    php:
        build: ./vendor/viezel/dock/runtimes/8.0
        working_dir: /var/www/html
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - '.:/var/www/html'
        depends_on:
            - mysql
            - redis
        networks:
            - dock

    mysql:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - dock
        volumes:
            - 'dockmysql:/var/lib/mysql'
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping" ]

    queue:
        image: redis
        networks:
            - dock
        volumes:
            - 'dockqueue:/data'

    redis:
        image: redis
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        networks:
            - dock
        volumes:
            - 'dockredis:/data'
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]

    mailhog:
        image: mailhog/mailhog:latest
        ports:
            - '${FORWARD_MAILHOG_PORT:-1025}:1025'
            - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
        networks:
            - dock

networks:
    dock:
        driver: bridge

volumes:
    dockmysql:
        driver: local
    dockqueue:
        driver: local
    dockredis:
        driver: local
